name: Testing before pull request

on: 
  pull_request:
    branches: 
      - main
      
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: mvn test
